// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXPK_yTePp90gBWicNOJnpfdDcid2SyNc',
    appId: '1:364619032528:web:0c2e5bab0eeccff3c87bd5',
    messagingSenderId: '364619032528',
    projectId: 'currensee-399f1',
    authDomain: 'currensee-399f1.firebaseapp.com',
    databaseURL: 'https://currensee-399f1-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'currensee-399f1.appspot.com',
    measurementId: 'G-4Q8HW6D786',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRqmTvzm3GJKed0zk3SEZLIL6ph4cpcE',
    appId: '1:364619032528:android:881429319f3a630cc87bd5',
    messagingSenderId: '364619032528',
    projectId: 'currensee-399f1',
    databaseURL: 'https://currensee-399f1-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'currensee-399f1.appspot.com',
  );
}
